# Generated by Django 5.2.12 on 2026-04-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_credithistory_is_active_credithistory_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='credithistory',
            name='credit_plan',
        ),
        migrations.RemoveField(
            model_name='credithistory',
            name='stripe_customer',
        ),
        migrations.RemoveField(
            model_name='invoicehistory',
            name='stripe_customer',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='stripe_customer',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='subscription_plan',
        ),
        migrations.CreateModel(
            name='CheckoutSessionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('subscription', 'Subscription'), ('credit', 'Credit'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_session_statuses', to='payments.stripecustomer')),
            ],
            options={
                'verbose_name_plural': 'checkout session statuses',
            },
        ),
        migrations.CreateModel(
            name='CreditStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_statuses', to='payments.creditplan')),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_statuses', to='payments.stripecustomer')),
            ],
            options={
                'verbose_name_plural': 'credit statuses',
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('stripe_payment_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_statuses', to='payments.stripecustomer')),
            ],
            options={
                'verbose_name_plural': 'invoice statuses',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_statuses', to='payments.stripecustomer')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_statuses', to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name_plural': 'subscription statuses',
            },
        ),
        migrations.DeleteModel(
            name='CheckoutSession',
        ),
        migrations.DeleteModel(
            name='CreditHistory',
        ),
        migrations.DeleteModel(
            name='InvoiceHistory',
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
    ]
