# Generated by Django 5.2.12 on 2026-04-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_webhookeventlog_remove_credithistory_credit_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsessionstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
