# Generated by Django 5.2.12 on 2026-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='stripe_subscription_id',
            field=models.CharField(max_length=255),
        ),
    ]
