# Generated by Django 5.2.12 on 2026-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_subscriptionhistory_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('credit', 'Credit'), ('custom', 'Custom')], max_length=20),
        ),
    ]
