# Generated by Django 5.2.12 on 2026-04-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_checkoutsession_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credithistory',
            name='is_active',
        ),
        migrations.AddField(
            model_name='credithistory',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='stripe_subscription_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('stripe_payment_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_histories', to='payments.stripecustomer')),
            ],
        ),
    ]
