# Generated by Django 5.2.12 on 2026-04-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_checkoutsessionstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsessionstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
